name: EP
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.9
    - pip
    - pip:
          - eppy
    - pandas
    - pyyaml
    - rich
    - loguru
    - click
    - yapf
    - toml
    - isort
    - pylint
    - mypy
